# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.ClassesType', verbose_name='\u0422\u0438\u043f \u043f\u0440\u0435\u0434\u043c\u0435\u0442\u0430'),
        ),
    ]
