# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 10:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_teacher_all_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='course',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='semester',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_group',
            field=models.ManyToManyField(to='core.Group', verbose_name='\u0413\u0440\u0443\u043f\u043f\u044b'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_connection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_group_full_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Group', verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430 \u0441\u0442\u0443\u0434\u0435\u043d\u0442\u0430'),
        ),
    ]
