# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classestype',
            name='classes_type',
            field=models.CharField(choices=[('Лекции', 'Лекции'), ('Семинары', 'Семинары'), ('Консультации', 'Консультации'), ('Лабораторные', 'Лабораторные'), ('Контрольно-проверочные мероприятия', 'Контрольно-проверочные мероприятия')], max_length=40, verbose_name='Тип занятий'),
        ),
    ]
