# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 12:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npd', '__first__'),
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPDMark',
            fields=[
                ('mark_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marks.Mark')),
                ('difficult_points', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='\u0423\u0440\u043e\u0432\u0435\u043d\u044c \u0441\u043b\u043e\u0436\u043d\u043e\u0441\u0442\u0438')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npd.NPD', verbose_name='\u041d\u041f\u0414')),
            ],
            bases=('marks.mark',),
        ),
    ]
