# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0004_auto_20161212_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='who_rated',
        ),
        migrations.AddField(
            model_name='mark',
            name='type_rated',
            field=models.CharField(choices=[(b't', '\u041f\u0440\u0435\u043f\u043e\u0434\u0430\u0432\u0430\u0442\u0435\u043b\u044c'), (b's', '\u0421\u0442\u0443\u0434\u0435\u043d\u0442'), (b'a', '\u0410\u0434\u043c\u0438\u043d\u0438\u0441\u0442\u0440\u0430\u0442\u043e\u0440')], default=b's', max_length=2, verbose_name='\u0422\u0438\u043f \u043e\u0446\u0435\u043d\u0438\u0432\u0448\u0435\u0433\u043e'),
        ),
    ]
