# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0005_auto_20161214_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmark',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Student', verbose_name='\u041e\u0446\u0435\u043d\u0438\u0432\u0448\u0438\u0439'),
        ),
        migrations.AlterField(
            model_name='subjectmark',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Subject', verbose_name='\u041e\u0446\u0435\u043d\u0438\u0432\u0448\u0438\u0439'),
        ),
        migrations.AlterField(
            model_name='teachermark',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Teacher', verbose_name='\u041e\u0446\u0435\u043d\u0438\u0432\u0448\u0438\u0439'),
        ),
    ]
