# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 13:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npd', '0003_remove_npd_who'),
        ('marks', '0008_subjectmark_what_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='npdmark',
            name='what_npd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='npd.NPD', verbose_name='\u041d\u041f\u0414'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='npdmark',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041a\u0442\u043e \u043e\u0446\u0435\u043d\u0438\u043b'),
        ),
    ]
