# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 12:29
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20161212_1354'),
        ('marks', '0009_auto_20161214_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Krit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u0414\u0430\u0442\u0430 \u0437\u0430\u0432\u0435\u0434\u0435\u043d\u0438\u044f')),
                ('name', models.TextField(default=b'Default name', verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u043a\u0440\u0438\u0442\u0435\u0440\u0438\u044f')),
                ('type', models.CharField(choices=[(b't', '\u041f\u0440\u0435\u043f\u043e\u0434\u0430\u0432\u0430\u0442\u0435\u043b\u044c'), (b's', '\u0421\u0442\u0443\u0434\u0435\u043d\u0442'), (b'a', '\u0410\u0434\u043c\u0438\u043d\u0438\u0441\u0442\u0440\u0430\u0442\u043e\u0440'), (b'p', '\u041f\u0440\u0435\u0434\u043c\u0435\u0442'), (b'n', '\u041d\u041f\u0414')], default=b'p', max_length=2, verbose_name='\u041e\u0446\u0435\u043d\u0438\u0432\u0430\u0435\u043c\u0430\u044f \u0441\u0443\u0449\u043d\u043e\u0441\u0442\u044c')),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u0414\u0430\u0442\u0430 \u0437\u0430\u0432\u0435\u0434\u0435\u043d\u0438\u044f')),
                ('name', models.TextField(default=b'Default scale', verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u0448\u043a\u0430\u043b\u044b')),
                ('max_value', models.IntegerField(default=10, verbose_name='\u041c\u0430\u043a\u0441\u0438\u043c\u0430\u043b\u044c\u043d\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435')),
                ('min_value', models.IntegerField(default=1, verbose_name='\u041c\u0438\u043d\u0438\u043c\u0430\u043b\u044c\u043d\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435')),
            ],
        ),
        migrations.RemoveField(
            model_name='npdmark',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='npdmark',
            name='mark_ptr',
        ),
        migrations.RemoveField(
            model_name='npdmark',
            name='what_npd',
        ),
        migrations.RemoveField(
            model_name='studentmark',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='studentmark',
            name='mark_ptr',
        ),
        migrations.RemoveField(
            model_name='subjectmark',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='subjectmark',
            name='mark_ptr',
        ),
        migrations.RemoveField(
            model_name='subjectmark',
            name='what_subject',
        ),
        migrations.RemoveField(
            model_name='teachermark',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='teachermark',
            name='mark_ptr',
        ),
        migrations.AddField(
            model_name='mark',
            name='mark_value',
            field=models.IntegerField(default=b'1', verbose_name='\u041e\u0446\u0435\u043d\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='mark',
            name='subject_marked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Subject'),
        ),
        migrations.AddField(
            model_name='mark',
            name='type_marked',
            field=models.CharField(choices=[(b't', '\u041f\u0440\u0435\u043f\u043e\u0434\u0430\u0432\u0430\u0442\u0435\u043b\u044c'), (b's', '\u0421\u0442\u0443\u0434\u0435\u043d\u0442'), (b'a', '\u0410\u0434\u043c\u0438\u043d\u0438\u0441\u0442\u0440\u0430\u0442\u043e\u0440'), (b'p', '\u041f\u0440\u0435\u0434\u043c\u0435\u0442'), (b'n', '\u041d\u041f\u0414')], default=b's', max_length=2, verbose_name='\u0422\u0438\u043f \u043e\u0446\u0435\u043d\u0438\u0432\u0430\u0435\u043c\u043e\u0433\u043e'),
        ),
        migrations.AddField(
            model_name='mark',
            name='user_marked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_whom_marked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mark',
            name='user_rated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_that_rated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mark',
            name='type_rated',
            field=models.CharField(choices=[(b't', '\u041f\u0440\u0435\u043f\u043e\u0434\u0430\u0432\u0430\u0442\u0435\u043b\u044c'), (b's', '\u0421\u0442\u0443\u0434\u0435\u043d\u0442'), (b'a', '\u0410\u0434\u043c\u0438\u043d\u0438\u0441\u0442\u0440\u0430\u0442\u043e\u0440'), (b'p', '\u041f\u0440\u0435\u0434\u043c\u0435\u0442'), (b'n', '\u041d\u041f\u0414')], default=b's', max_length=2, verbose_name='\u0422\u0438\u043f \u043e\u0446\u0435\u043d\u0438\u0432\u0448\u0435\u0433\u043e'),
        ),
        migrations.DeleteModel(
            name='NPDMark',
        ),
        migrations.DeleteModel(
            name='StudentMark',
        ),
        migrations.DeleteModel(
            name='SubjectMark',
        ),
        migrations.DeleteModel(
            name='TeacherMark',
        ),
        migrations.AddField(
            model_name='krit',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.Scale'),
        ),
        migrations.AddField(
            model_name='mark',
            name='criterion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marks.Krit'),
        ),
    ]
