# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 11:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0010_auto_20161216_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krit',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.Scale', verbose_name='\u0428\u043a\u0430\u043b\u0430'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='criterion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marks.Krit', verbose_name='\u041a\u0440\u0438\u0442\u0435\u0440\u0438\u0439'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='subject_marked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Subject', verbose_name='\u041e\u0446\u0435\u043d\u0438\u0432\u0430\u0435\u043c\u044b\u0439 \u043f\u0440\u0435\u0434\u043c\u0435\u0442'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='user_marked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_whom_marked', to=settings.AUTH_USER_MODEL, verbose_name='\u041a\u043e\u0433\u043e \u043e\u0446\u0435\u043d\u0438\u0432\u0430\u0435\u043c'),
        ),
    ]
