# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0010_mark_who_rated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npdmark',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='subjectmark',
            name='mark',
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Student', verbose_name='\u041a\u0430\u043a\u043e\u0439 \u0441\u0442\u0443\u0434\u0435\u043d\u0442'),
        ),
        migrations.AlterField(
            model_name='subjectmark',
            name='what_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Subject', verbose_name='\u041a\u0430\u043a\u043e\u0439 \u043f\u0440\u0435\u0434\u043c\u0435\u0442'),
        ),
        migrations.AlterField(
            model_name='teachermark',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Teacher', verbose_name='\u041a\u0430\u043a\u043e\u0439 \u043f\u0440\u0435\u043f\u043e\u0434\u0430\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
    ]
