# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 11:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0011_auto_20161219_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='user_rated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_that_rated', to=settings.AUTH_USER_MODEL, verbose_name='\u041a\u0442\u043e \u043e\u0446\u0435\u043d\u0438\u043b'),
        ),
    ]
