# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0012_auto_20161219_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='krit',
            options={'verbose_name': '\u041a\u0440\u0438\u0442\u0435\u0440\u0438\u0439', 'verbose_name_plural': '\u041a\u0440\u0438\u0442\u0435\u0440\u0438\u0438'},
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={'verbose_name': '\u041e\u0446\u0435\u043d\u043a\u0430', 'verbose_name_plural': '\u041e\u0446\u0435\u043d\u043a\u0438'},
        ),
        migrations.AlterModelOptions(
            name='scale',
            options={'verbose_name': '\u0428\u043a\u0430\u043b\u0430', 'verbose_name_plural': '\u0428\u043a\u0430\u043b\u044b'},
        ),
    ]
