# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npd', '0003_remove_npd_who'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='npd',
            options={'verbose_name': '\u041d\u0430\u0443\u0447\u043d\u043e-\u043f\u0440\u0430\u043a\u0442\u0438\u0447\u0435\u0441\u043a\u0430\u044f \u0434\u0435\u044f\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c', 'verbose_name_plural': '\u041d\u0430\u0443\u0447\u043d\u043e-\u043f\u0440\u0430\u043a\u0442\u0438\u0447\u0435\u0441\u043a\u0438\u0435 \u0434\u0435\u044f\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u0438'},
        ),
    ]
